### ISSUE TITLE
Suggestions not working after upgrading from 1.2.0 to 1.2.1

### ISSUE THREAD

**Issue by stefan-sachs** [RBMHTechnology/vind#62]
We did an upgrade from vind 1.2.0 to vind 1.2.1 and updated all our collections to the new config version. Unfortunately the suggestions do not work anymore after the upgrade.

```
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://....: java.lang.IllegalStateException: Type mismatch: dynamic_multi_stored_suggest_string_company was indexed as SORTED_SET
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:372)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:325)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1121)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:891)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:827)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
        at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:974)
        at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:990)
        at com.rbmhtechnology.vind.solr.backend.SolrSearchServer.execute(SolrSearchServer.java:817)
        at com.rbmhtechnology.vind.solr.backend.SolrSearchServer.execute(SolrSearchServer.java:808)
        at com.rbmhtechnology.vind.monitoring.MonitoringSearchServer.execute(MonitoringSearchServer.java:349)
        at com.rbmhtechnology.vind.monitoring.MonitoringSearchServer.execute(MonitoringSearchServer.java:342)
```

Indexing the data did not solve the problem. Removing all the documents and indexing seems to solve it. However, due to the amount of data that is not an option for us. 

Please provide a way we can do the upgrade without deleting all the data from the index.

**Comment by alfonso-noriega** [comment]
In releases < `1.2.0` schema, the suggestion string field was configured as:
`<dynamicField name="dynamic_multi_stored_suggest_string_*" type="string" multiValued="true" indexed="true" stored="true"/>`
After realizing the need to handle special characters as one  (_'_ ,_\`_, _’_,..) pointed out in __Vind__ issue #39, the field definition was changed to _string_suggest_, a text type with some analyzers defined:
`<dynamicField name="dynamic_multi_stored_suggest_string_*" type="string_suggest" multiValued="true" indexed="true" stored="true"/>` 
On upgrade of an exisiting Solr collection seems like this change needs of a complete deletion and index to avoid a conflict between the existing type and the new schema. 

As a deletion of the index is not normally an option in a many scenarios __Vind__ schema has rolled back to the previous suggestion field definition and added a new field  _suggestion_analyzed_, which will be used from release `1.2.3` on by default for suggestions.
`<dynamicField name="dynamic_single_stored_suggest_analyzed_*" type="string_suggest" 
multiValued="false" indexed="true" stored="true"/>`

When upgrading from a previous version a full re-index is needed in order to have suggestions provided again, but no error should show until this is done.
